name: Dependabot auto squash-merge
on:
  pull_request:
permissions:
  pull-requests: write
  contents: write
jobs:
  add_comment:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v3
      - name: Add comment to PR by Dependabot
        uses: octokit/action-comment@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment: |
            @dependabot rebase
            @dependabot squash and merge
